# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ffdacbb20df8ac63150fb13791e188ebd5bb8c1e59439887636c6cc728bab4f969c548e9a06b1d6a3813e86195f020b10778111825feefe751e7385f207cf14

test:
  secret_key_base: e18edd6a0bb967a8ef2478ed6eaf38128ccfb592a68bafc29e169b79862b67d222070f61a754439b693bf57e9ff72474a5f5b6b11d116ad413b0c2d167f716aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
